// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "gui.h"

Fl_Double_Window *game_window=(Fl_Double_Window *)0;

Fl_Output *hp_input=(Fl_Output *)0;

Fl_Output *str_input=(Fl_Output *)0;

Fl_Output *dex_input=(Fl_Output *)0;

Fl_Output *con_input=(Fl_Output *)0;

Fl_Output *int_input=(Fl_Output *)0;

Fl_Output *wis_input=(Fl_Output *)0;

Fl_Output *cha_input=(Fl_Output *)0;

Fl_Output *ac_input=(Fl_Output *)0;

Fl_Browser *ItemInventory=(Fl_Browser *)0;

Fl_Group *map_group=(Fl_Group *)0;

Fl_Group *enemies_group=(Fl_Group *)0;

Fl_Browser *turn_order=(Fl_Browser *)0;

Fl_Double_Window* make_window() {
  { game_window = new Fl_Double_Window(1920, 1008, "Game");
    { Fl_Pack* o = new Fl_Pack(0, 0, 1920, 1130);
      o->type(1);
      { Fl_Group* o = new Fl_Group(0, 50, 288, 1080, "Player");
        { Fl_Group* o = new Fl_Group(0, 62, 288, 200, "Stats");
          { hp_input = new Fl_Output(60, 62, 50, 50, "HP");
            hp_input->box(FL_ENGRAVED_FRAME);
          } // Fl_Output* hp_input
          { str_input = new Fl_Output(60, 112, 50, 50, "STR");
            str_input->box(FL_ENGRAVED_FRAME);
          } // Fl_Output* str_input
          { dex_input = new Fl_Output(160, 112, 50, 50, "DEX");
            dex_input->box(FL_ENGRAVED_FRAME);
          } // Fl_Output* dex_input
          { con_input = new Fl_Output(60, 162, 50, 50, "CON");
            con_input->box(FL_ENGRAVED_FRAME);
          } // Fl_Output* con_input
          { int_input = new Fl_Output(160, 162, 50, 50, "INT");
            int_input->box(FL_ENGRAVED_FRAME);
          } // Fl_Output* int_input
          { wis_input = new Fl_Output(60, 212, 50, 50, "WIS");
            wis_input->box(FL_ENGRAVED_FRAME);
          } // Fl_Output* wis_input
          { cha_input = new Fl_Output(160, 212, 50, 50, "CHA");
            cha_input->box(FL_ENGRAVED_FRAME);
          } // Fl_Output* cha_input
          { ac_input = new Fl_Output(160, 62, 50, 50, "AC");
            ac_input->box(FL_ENGRAVED_FRAME);
          } // Fl_Output* ac_input
          o->end();
        } // Fl_Group* o
        { ItemInventory = new Fl_Browser(10, 315, 200, 600, "Inventory");
          ItemInventory->box(FL_DOWN_BOX);
          ItemInventory->labelfont(1);
        } // Fl_Browser* ItemInventory
        o->end();
      } // Fl_Group* o
      { map_group = new Fl_Group(288, 0, 1344, 1026, "Map");
        map_group->end();
      } // Fl_Group* map_group
      { enemies_group = new Fl_Group(1632, 0, 288, 1030, "Enemies");
        { turn_order = new Fl_Browser(1655, 599, 231, 300, "Turn Order");
          turn_order->labelfont(1);
        } // Fl_Browser* turn_order
        enemies_group->end();
      } // Fl_Group* enemies_group
      o->end();
    } // Fl_Pack* o
    game_window->end();
  } // Fl_Double_Window* game_window
  return game_window;
}
