// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include "Main.h"
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *game_window;
#include <FL/Fl_Pack.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Output.H>
extern Fl_Output *hp_input;
extern Fl_Output *str_input;
extern Fl_Output *dex_input;
extern Fl_Output *con_input;
extern Fl_Output *int_input;
extern Fl_Output *wis_input;
extern Fl_Output *cha_input;
extern Fl_Output *ac_input;
#include <FL/Fl_Browser.H>
extern Fl_Browser *ItemInventory;
extern Fl_Group *map_group;
extern Fl_Group *enemies_group;
extern Fl_Browser *turn_order;
Fl_Double_Window* make_window();
#endif
